name: github-actions-build-plan
run-name: Build ${{ github.run_number }} for secblogs
on: 
  schedule:
   - cron: "*/30 * * * *" # Every 30 min
jobs:
  build-html-file:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - run: go run main.go
